### ISSUE TITLE
Is it possible to have an updated version of this tutorial ?

### ISSUE THREAD

**Issue by ghost** [tonysm/dockerforlaravel-app#2]
Hello. Amazing work. Really.

Do you plan to release a new 2022 updated version ?

**Comment by ghost** [comment]
Possible new topics: auto-scaling (hpa), mongodb, firewall, multi-cloud providers.

**Comment by tonysm** [comment]
Hey, @zenati. Thanks for the comment. Unfortunately, no plans to update the series.
